apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: docker
  name: techtrends-docker
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
        labels:
            app: techtrends
    spec:
      containers:
      - name: {{ .Values.namespace.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbePath }}
            port: 3111
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe }}
            port: 3111
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
